name: Quarkus-Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to checkout when cutting the release."
        required: true
        default: "main"
      increment-major:
        description: "Should we increment the major version (true/false)"
        required: true
        default: "false"
      increment-minor:
        description: "Should we increment the minor version (true/false)"
        required: true
        default: "false"
defaults:
  run:
    working-directory: release/DataTier-APIs/Quarkus-APIs

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.HEROPHILUS_ACCESS_TOKEN }}
        path: release
    - name: Java Maven release
      id: maven-release
      uses: qcastel/github-actions-maven-release@v1.12.16
      env:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk/
      with:
        access-token: ${{ secrets.HEROPHILUS_ACCESS_TOKEN }}
        release-branch-name: ${{ github.event.inputs.branch }}
        version-major: ${{ github.event.inputs.increment-major }}
        version-minor: ${{ github.event.inputs.increment-minor }}
        maven-args: "-Dmaven.deploy.skip=true"
        git-release-bot-name: "idaas-bot"
        maven-project-folder: release/DataTier-APIs/Quarkus-APIs
    - uses: octokit/request-action@v2.x
      id: get_latest_tag
      with:
        route: GET /repos/jayfray12/DataSynthesis-1/tags
        owner: jayfray12
        repo: DataSynthesis-1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: echo ::set-output name=tag_name::$(echo '${{ steps.get_latest_tag.outputs.data }}' | jq .[-1].name -r)
      id: tag-name
    - run: "echo Tag: ${{ steps.tag-name.outputs.tag_name }}"
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.HEROPHILUS_ACCESS_TOKEN }}
        path: tag
        ref: refs/tags/${{ steps.tag-name.outputs.tag_name }}
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: "Build & test"
      run: mvn -B package -Dquarkus.package.type=uber-jar --file pom.xml
      working-directory: tag/DataTier-APIs/Quarkus-APIs
      env:
        GITHUB_TOKEN: ${{ secrets.HEROPHILUS_ACCESS_TOKEN }}
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        automatic_release_tag: ${{ steps.tag-name.outputs.tag_name }}
        repo_token: "${{ secrets.HEROPHILUS_ACCESS_TOKEN }}"
        prerelease: false
        files: |
          tag/DataTier-APIs/Quarkus-APIs/target/*.jar

